"""Add UserRole enum and cascade deletes

Revision ID: 3d0487d7740b
Revises: 5b99bae68dca
Create Date: 2026-05-25 15:13:36.254702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0487d7740b'
down_revision: Union[str, None] = '5b99bae68dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.drop_constraint('dashboards_user_id_fkey', 'dashboards', type_='foreignkey')
    op.drop_constraint('dashboards_organization_id_fkey', 'dashboards', type_='foreignkey')
    op.create_foreign_key(None, 'dashboards', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dashboards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.execute("UPDATE users SET role = 'Owner' WHERE LOWER(role) = 'owner'")
    op.execute("UPDATE users SET role = 'Admin' WHERE LOWER(role) = 'admin'")
    op.execute("UPDATE users SET role = 'Analyst' WHERE LOWER(role) = 'analyst'")
    op.execute("UPDATE users SET role = 'Viewer' WHERE LOWER(role) = 'viewer'")
    
    op.execute("DROP TYPE IF EXISTS roleenum CASCADE")
    
    op.execute("CREATE TYPE roleenum AS ENUM ('Owner', 'Admin', 'Analyst', 'Viewer')")
    
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE roleenum USING role::text::roleenum")
               
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='roleenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.create_foreign_key('dashboards_organization_id_fkey', 'dashboards', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('dashboards_user_id_fkey', 'dashboards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
